name: Continuous Integration

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: |
          echo Hello World!
          Add other actions to Build
          echo test deploy your project
